#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES — hosted Supabase for blueberry-academy (issue #47)
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

REPO=$(git rev-parse --show-toplevel)
cd "$REPO"

ENV_FILE="$REPO/.env.hosted"
APP_ENV_FILE="$REPO/apps/web/.env.hosted"

for bin in supabase jq curl; do
  command -v "$bin" >/dev/null 2>&1 || { printf 'missing %s — install it first\n' "$bin"; exit 1; }
done

# http_code URL [curl args…] — the status code only, for the checks below.
http_code() { curl -s -o /dev/null -w '%{http_code}' "$@"; }

banner "blueberry-academy — hosted Supabase"

# ── 1 ────────────────────────────────────────────────────────────────────
stage "建立 hosted 專案"

SUPABASE_PROJECT_REF=$(_existing SUPABASE_PROJECT_REF || true)

if [[ -n "$SUPABASE_PROJECT_REF" ]]; then
  note "$ENV_FILE 已經有 ref $SUPABASE_PROJECT_REF — 跳過建立"
  SUPABASE_DB_PASSWORD=$(_existing SUPABASE_DB_PASSWORD || true)
else
  say "免費版一個組織最多兩個 active 專案。先看看現況："
  supabase projects list || true
  printf '\n'
  say "你有權限的組織："
  supabase orgs list || true
  printf '\n'
  ask SUPABASE_ORG_ID "要在哪個組織的 ID 底下建立："
  [[ -n "$SUPABASE_ORG_ID" ]] || { warn "沒有組織 ID 就建不了專案。"; exit 1; }
  ask SUPABASE_PROJECT_NAME "專案名稱 [Enter 用 blueberry-academy]:"
  [[ -z "$SUPABASE_PROJECT_NAME" ]] && SUPABASE_PROJECT_NAME="blueberry-academy"

  SUPABASE_DB_PASSWORD=$(openssl rand -base64 32 | tr -dc 'A-Za-z0-9' | cut -c1-28)
  note "DB 密碼由這支腳本生成，只會寫進 ${ENV_FILE}（gitignored），不會印在螢幕上。"

  confirm "要在 $SUPABASE_ORG_ID 建立 '$SUPABASE_PROJECT_NAME' 嗎？" || {
    warn "取消。"; exit 1
  }

  ask SUPABASE_REGION "region [Enter 用 ap-southeast-1]:"
  [[ -z "$SUPABASE_REGION" ]] && SUPABASE_REGION="ap-southeast-1"

  supabase projects create "$SUPABASE_PROJECT_NAME" \
    --org-id "$SUPABASE_ORG_ID" \
    --region "$SUPABASE_REGION" \
    --db-password "$SUPABASE_DB_PASSWORD"

  SUPABASE_PROJECT_REF=$(supabase projects list -o json \
    | jq -r --arg n "$SUPABASE_PROJECT_NAME" \
        '[.[] | select(.name == $n)] | sort_by(.created_at) | last | .id // .ref // empty')

  if [[ -z "$SUPABASE_PROJECT_REF" ]]; then
    warn "抓不到新專案的 ref。dashboard 的 URL 裡就是它：/project/<ref>"
    open_url "https://supabase.com/dashboard/projects"
    ask SUPABASE_PROJECT_REF "貼上 project ref："
  fi

  write_env SUPABASE_PROJECT_REF "$SUPABASE_PROJECT_REF"
  write_env SUPABASE_DB_PASSWORD "$SUPABASE_DB_PASSWORD"
  say "專案正在 provision，通常一兩分鐘。"
fi

if [[ -z "${SUPABASE_DB_PASSWORD:-}" ]]; then
  # link 用它連遠端 Postgres。專案已存在但密碼不在檔案裡時，只能問。
  ask_secret SUPABASE_DB_PASSWORD "這個專案的 DB 密碼："
  write_env SUPABASE_DB_PASSWORD "$SUPABASE_DB_PASSWORD"
fi

SUPABASE_URL="https://${SUPABASE_PROJECT_REF}.supabase.co"
pause "專案在 dashboard 上顯示 healthy 之後按 Enter"

# ── 2 ────────────────────────────────────────────────────────────────────
stage "link 專案並取得 API keys"

supabase link --project-ref "$SUPABASE_PROJECT_REF" --password "$SUPABASE_DB_PASSWORD"

KEYS=$(supabase projects api-keys --project-ref "$SUPABASE_PROJECT_REF" -o json 2>/dev/null || echo '[]')
printf '\n'
say "這個專案上的 keys："
printf '%s\n' "$KEYS" | jq -r '.[] | "  - \(.name)"' || true
printf '\n'

PUBLIC_KEY=$(printf '%s' "$KEYS" | jq -r \
  '[.[] | select(.name == "anon" or .name == "publishable")][0] | (.api_key // .apiKey // .value // empty)')
SECRET_KEY=$(printf '%s' "$KEYS" | jq -r \
  '[.[] | select(.name == "service_role" or .name == "secret")][0] | (.api_key // .apiKey // .value // empty)')

if [[ -z "$PUBLIC_KEY" || -z "$SECRET_KEY" ]]; then
  warn "CLI 沒給齊 keys — 從 dashboard 複製。"
  open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/settings/api-keys"
  [[ -z "$PUBLIC_KEY" ]] && ask PUBLIC_KEY "貼上 anon / publishable key（可公開）："
  [[ -z "$SECRET_KEY" ]] && ask_secret SECRET_KEY "貼上 service_role / secret key（絕不進 repo）："
fi

write_env SUPABASE_URL "$SUPABASE_URL"
write_env SUPABASE_SERVICE_ROLE_KEY "$SECRET_KEY"

# 前端要的兩個值分開放：apps/web 是 Nuxt 讀 dotenv 的地方。
ENV_FILE="$APP_ENV_FILE"
write_env NUXT_PUBLIC_SUPABASE_URL "$SUPABASE_URL"
write_env NUXT_PUBLIC_SUPABASE_ANON_KEY "$PUBLIC_KEY"
ENV_FILE="$REPO/.env.hosted"

note "service_role 只活在 $ENV_FILE 與你的 shell 裡。兩個檔案都被 .gitignore 的 .env.* 蓋住。"
pause

# ── 3 ────────────────────────────────────────────────────────────────────
stage "把 migrations 推上去"

say "同一份 supabase/migrations/ —— schema、RLS policy、replay-logs bucket 都在裡面。"
say "CLI 會先列出要跑的 migration 再問你要不要繼續。"
printf '\n'

if ! supabase db push; then
  warn "push 失敗了。"
  note "如果錯在 storage.objects 的 policy（must be owner of table objects）："
  note "  1. 到 SQL editor 把 data_floor.sql 最後那段 create policy 貼上去跑"
  note "  2. supabase migration repair --status applied <version>"
  open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/sql/new"
  confirm "處理完了，繼續？" || exit 1
fi

printf '\n'
say "遠端已套用的 migration："
supabase migration list --linked || true
pause

# ── 4 ────────────────────────────────────────────────────────────────────
stage "驗證 schema、bucket 與 grants"

say "用 service_role 打 REST，看資料層真的在線上成立。"
printf '\n'

CODE=$(http_code "${SUPABASE_URL}/rest/v1/battles?select=id,regulation,bring_complete&limit=1" \
  -H "apikey: ${SECRET_KEY}" -H "Authorization: Bearer ${SECRET_KEY}")
if [[ "$CODE" == "200" ]]; then
  printf '  %s✓%s battles 可讀，regulation generated column 在（200）\n' "$GREEN" "$RESET"
else
  warn "battles 回 $CODE — schema 沒到位"
fi

BUCKETS=$(curl -s "${SUPABASE_URL}/storage/v1/bucket" \
  -H "apikey: ${SECRET_KEY}" -H "Authorization: Bearer ${SECRET_KEY}")
if printf '%s' "$BUCKETS" | jq -e '.[] | select(.id == "replay-logs")' >/dev/null 2>&1; then
  printf '  %s✓%s replay-logs bucket 在，public=%s\n' "$GREEN" "$RESET" \
    "$(printf '%s' "$BUCKETS" | jq -r '.[] | select(.id == "replay-logs") | .public')"
else
  warn "replay-logs bucket 不在 — 沒有它就沒有 reparse"
fi

# 有沒有 SELECT 權限跟誰讀得到列是兩件事：hosted 會把 public schema 新表的預設
# 權限給 anon（見 config.toml 的 auto_expose_new_tables），所以 401 跟 200 都可能。
# 沒回列才是保證 —— RLS 是防線，grant 只是門。
ANON_BODY=$(curl -s "${SUPABASE_URL}/rest/v1/battles?select=id&limit=1" \
  -H "apikey: ${PUBLIC_KEY}" -H "Authorization: Bearer ${PUBLIC_KEY}")
ANON_ROWS=$(printf '%s' "$ANON_BODY" | jq -r 'if type == "array" then length else "denied" end' 2>/dev/null || echo "denied")
if [[ "$ANON_ROWS" == "denied" ]]; then
  printf '  %s✓%s 未登入的 anon 在權限層就被拒了\n' "$GREEN" "$RESET"
elif [[ "$ANON_ROWS" == "0" ]]; then
  printf '  %s✓%s anon 讀不到任何 battles，RLS 濾掉了所有列\n' "$GREEN" "$RESET"
  note "但它還握著 select 權限：20260824174500_close_the_door_on_anon.sql 還沒推上去（supabase db push）"
else
  warn "anon 讀到 $ANON_ROWS 筆 battles — RLS 破了，停下來別往下走"
fi
pause

# ── 5 ────────────────────────────────────────────────────────────────────
stage "Google OAuth — 加上 hosted 專案的 callback"

say "沿用本機那組 OAuth client，只多一條 redirect URI。"
printf '\n'
step "打開 Credentials → 你的 Web application OAuth 2.0 Client ID"
step "Authorised redirect URIs → ADD URI，貼上："
printf '\n      %s%s/auth/v1/callback%s\n\n' "$BOLD" "$SUPABASE_URL" "$RESET"
step "SAVE。（Google 有時要幾分鐘才生效。）"
note "本機那條 http://127.0.0.1:54321/auth/v1/callback 留著，兩邊共用同一組 client。"
printf '\n'
open_url "https://console.cloud.google.com/apis/credentials"
pause "加好並儲存後按 Enter"

# ── 6 ────────────────────────────────────────────────────────────────────
stage "推 Auth 設定（config.toml，不是在 Studio 點的）"

if [[ -f "$REPO/supabase/.env" ]]; then
  set -a; . "$REPO/supabase/.env"; set +a
  note "已載入 supabase/.env 的 Google client id / secret"
  # 那個檔案是給 CLI 讀的，可能也放了自己的 SUPABASE_URL。這裡認的只有這個專案。
  SUPABASE_URL="https://${SUPABASE_PROJECT_REF}.supabase.co"
else
  warn "找不到 supabase/.env — config push 會把 google 的 client_id 推成空的"
  confirm "還是要繼續？" || exit 1
fi

say "會推上去的重點：google provider 開、[auth.email] enable_signup = false、"
say "redirect allowlist = localhost:3000（正式 origin 等 #48 部署後再補）。"
warn "config push 會用 config.toml 覆蓋遠端設定 — 它會先給你 diff 再問。"
printf '\n'

supabase config push || warn "config push 沒成功，往下的驗證會照實反映"

printf '\n'
SETTINGS=$(curl -s "${SUPABASE_URL}/auth/v1/settings" -H "apikey: ${PUBLIC_KEY}")
printf '  google=%s  email=%s\n' \
  "$(printf '%s' "$SETTINGS" | jq -r '.external.google')" \
  "$(printf '%s' "$SETTINGS" | jq -r '.external.email')"
note "要的是 google=true、email=false（沒有密碼登入）。"
note "config.toml 的 skip_nonce_check = true 是本機 Google 登入需要的，hosted 不需要但無害。"
pause

# ── 7 ────────────────────────────────────────────────────────────────────
stage "用兩個真的 Google 帳號登入"

say "本機 dev server 打 hosted 專案，不動你原本的 apps/web/.env："
printf '\n      %scd apps/web && pnpm exec nuxt dev --dotenv .env.hosted%s\n\n' "$BOLD" "$RESET"
step "帳號 A：Google 登入，綁一個 Showdown 別名，匯入一場對戰"
step "帳號 B：換一個瀏覽器 profile 或無痕窗，同樣登入並匯入一場"
note "allowlist 現在只有 localhost:3000 / 127.0.0.1:3000，所以要從本機開。"
pause "兩個帳號都登入並各匯入一場之後按 Enter"

printf '\n'
USERS=$(curl -s "${SUPABASE_URL}/auth/v1/admin/users" \
  -H "apikey: ${SECRET_KEY}" -H "Authorization: Bearer ${SECRET_KEY}")
PROFILES=$(curl -s "${SUPABASE_URL}/rest/v1/profiles?select=id" \
  -H "apikey: ${SECRET_KEY}" -H "Authorization: Bearer ${SECRET_KEY}")

say "auth.users："
printf '%s' "$USERS" | jq -r '.users[]? | "  - \(.id)  \(.email)"' || true
U_COUNT=$(printf '%s' "$USERS" | jq -r '(.users // []) | length')
P_COUNT=$(printf '%s' "$PROFILES" | jq -r 'if type == "array" then length else 0 end')
if [[ "$U_COUNT" == "$P_COUNT" && "$U_COUNT" != "0" ]]; then
  printf '  %s✓%s users=%s profiles=%s — trigger 有把 profile 建出來\n' \
    "$GREEN" "$RESET" "$U_COUNT" "$P_COUNT"
else
  warn "users=$U_COUNT profiles=$P_COUNT — create_profile_on_signup 沒生效"
fi
pause

# ── 8 ────────────────────────────────────────────────────────────────────
stage "就地驗證 RLS：兩個帳號互相讀不到"

say "各自帳號的 battles 與 raw log 路徑（service_role 視角，繞過 RLS）："
printf '\n'
curl -s "${SUPABASE_URL}/rest/v1/battles?select=user_id,replay_id,log_path" \
  -H "apikey: ${SECRET_KEY}" -H "Authorization: Bearer ${SECRET_KEY}" \
  | jq -r '.[]? | "  \(.user_id)  \(.replay_id)  \(.log_path)"' || true
printf '\n'

ask OTHER_UID "要被偷看的那個 user id："
ask OTHER_LOG_PATH "那個人的 log_path（例如 <uid>/gen9xxx.json.gz）："

printf '\n'
say "在「另一個」帳號還登入著的瀏覽器 devtools console 貼這段（用的是它真的 JWT）："
printf '\n'
cat <<EOJS
  // 同一個 origin 上可能還留著本機 stack 的 session，所以按 project ref 挑，
  // 不是挑第一個 auth-token —— 拿錯 token 這個測試就變成在問別的問題。
  const key = 'sb-${SUPABASE_PROJECT_REF}-auth-token'
  const token = JSON.parse(localStorage[key] ?? 'null')?.access_token
  if (!token) throw new Error(key + ' 不在 localStorage 裡 —— 這個瀏覽器沒有登入 hosted 專案')
  const url = '${SUPABASE_URL}', anon = '${PUBLIC_KEY}'
  const h = { apikey: anon, Authorization: 'Bearer ' + token }
  const rows = await (await fetch(url + '/rest/v1/battles?select=id&user_id=eq.${OTHER_UID}', { headers: h })).json()
  const obj = await fetch(url + '/storage/v1/object/replay-logs/${OTHER_LOG_PATH}', { headers: h })
  console.log('對方的 battles 讀到幾筆（要 0）:', rows.length, '| raw log 狀態碼（要 4xx）:', obj.status)
EOJS
printf '\n'
note "兩個方向都跑一次：A 的瀏覽器看 B、B 的瀏覽器看 A。"
warn "任何一邊讀到 >0 筆或 raw log 回 200，就是 RLS/Storage policy 破了 —— 停下來修，別部署。"
pause "兩個方向都是 0 筆 / 4xx 之後按 Enter"

finish
note "下一步：#48 部署到 Cloudflare Workers，拿到正式 origin 之後把它加進"
note "config.toml 的 site_url / additional_redirect_urls 再 config push 一次。"
